FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

# System packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        locales \
        git \
        ninja-build \
        cmake \
        ca-certificates \
        build-essential \
        curl \
        unzip \
        sudo && \
    rm -rf /var/lib/apt/lists/*

# UTF-8 locale
RUN sed -i 's/^# *\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# ---------- Create qgcuser (non-root) ----------
ARG USERNAME=qgcuser
ARG USER_UID=1001
ARG USER_GID=1001

RUN groupadd --gid ${USER_GID} ${USERNAME} \
    && useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}
    
# Qt setup
COPY tools/setup/install-dependencies-debian.sh /tmp/qt/
COPY tools/setup/install-qt-debian.sh /tmp/qt/
RUN chmod +x /tmp/qt/*.sh && \
    /tmp/qt/install-dependencies-debian.sh && \
    /tmp/qt/install-qt-debian.sh && \
    rm -rf /tmp/qt

ENV QT_ROOT_DIR=/opt/Qt/6.10.0/gcc_64
ENV PATH=$QT_ROOT_DIR/bin:$PATH

RUN git config --global --add safe.directory /project/source

RUN mkdir -p /project/source /project/build \
    && chown -R ${USERNAME}:${USERNAME} /project

WORKDIR /project/build

USER ${USERNAME}

CMD ["bash", "-lc", "\
  qt-cmake -S /project/source -B /project/build -G Ninja -DCMAKE_BUILD_TYPE=Release && \
  cmake --build /project/build --target all --parallel && \
  cmake --install /project/build --config Release \
"]